### ISSUE TITLE
Email me when a new event is submitted

### ISSUE THREAD

**Issue by ericlbarnes** [laravelnews/laravelevents#7]
The app needs to email me when a new event is submitted so I'm reminded to go and check it out and approve/decline it.

**Comment by bvipul** [comment]
is it done by somebody else? I will add a PR today.
And the email address to email will be : eric@ericlbarnes.com, right?

**Comment by ericlbarnes** [comment]
It's all yours. :) 

For the address, I think it'd be best to just use the config/mail->from address.
